spring.application.name=ServeurTomcat
server.servlet.context-path=/
server.port=8080

spring.datasource.url=jdbc:sqlite:../serveurDeno/kanban.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=none
spring.docker.compose.enabled=${SPRING_DOCKER_COMPOSE_ENABLED:true}
spring.docker.compose.file=../docker-compose.yml
