spring.application.name=ServeurTomcat
server.servlet.context-path=/
server.port=8081

spring.datasource.url=jdbc:sqlite:../serveurDeno/kanban.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.packages-to-scan=com.kanban
spring.jpa.hibernate.ddl-auto=none
spring.mongodb.uri=${MONGO_URI}
spring.docker.compose.enabled=${SPRING_DOCKER_COMPOSE_ENABLED:true}
spring.docker.compose.file=../docker-compose.yml
management.endpoints.web.exposure.include=health,info,mappings
