services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    env_file:
      - ./client/.env
    ports:
      - "5173:80"
    depends_on:
      - serveur-deno
    networks:
      - appnet
    restart: always

  serveur-deno:
    build:
      context: ./serveurDeno
      dockerfile: Dockerfile
    env_file:
      - ./serveurDeno/.env
    volumes:
      - ./serveurDeno/kanban.db:/app/kanban.db
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - serveur-tomcat
    networks:
      - appnet
    restart: always

  serveur-tomcat:
    build:
      context: ./serveurTomcat
      dockerfile: Dockerfile
    env_file:
      - ./serveurTomcat/.env
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    networks:
      - appnet
    restart: always

  mongo:
    image: mongo:7.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongo_data:/data/db
    ports:
      - "27018:27017"
    networks:
      - appnet

volumes:
  mongo_data:

networks:
  appnet:
    driver: bridge
